server:
  address: 0.0.0.0
  port: 9097
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digitalWallet_db
    username: root
    password: victormutua17
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "qwertyuiopasdfghjklzxcvbnm1234567890!@#"
  expiration: 3600000
